version: "3.9" # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8080:8080"
    secrets: # secrets block only for 'web' service
      - SENDGRID_API_KEY
    environment:
      SENDGRID_API_KEY: "${sendGridApiKey}"
      SENDGRID_API: "${sendGridApiKey}"
secrets: # top level secrets block
  SENDGRID_API_KEY:
    external: true
